################################################################################
# GROMACS topology writer                                                      #
################################################################################

"""GROMACS topology and slit charge-diagnostic writer."""

import os

import silicams.database as db
import silicams.utils as utils
from silicams.topology import (
    BareSilicaChargeContribution,
    BareSilicaChargeDiagnostics,
    FunctionalizedSlitChargeDiagnostics,
    GromacsAngle,
    GromacsAtom,
    GromacsBond,
    GromacsDihedral,
    GromacsMoleculeType,
    GromacsPair,
    SilicaTopologyModel,
    default_silica_topology,
    parse_flat_itp,
    render_itp,
    render_top,
)

from .common import (
    _FULL_SLIT_NREXCL,
    _FUNCTIONALIZED_CHARGE_TOLERANCE,
    _format_decimal_token,
    _full_slit_mount_ligand_cross_angle_role,
    _sanitize_gromacs_identifier,
    _silica_assignment_role_name,
    _silica_atomtype_lookup,
    _silica_atomtypes_in_order,
)
from .structure import StructureWriter


class GromacsTopologyWriter(StructureWriter):
    """Write GROMACS helper or full-slit topology files.

    Parameters
    ----------
    inp : StructureSnapshot
        Finalized silica-slit export snapshot.
    link : str or os.PathLike, optional
        Output directory for generated files.
    """
    def write_helper_topology(self, name=""):
        """Write a molecule-count helper topology from a slit snapshot.

        The generated ``.top`` file includes molecule ``.itp`` files and the
        final molecule counts stored in the snapshot. Exported helper
        topologies normalize internal siloxane bridge ``SLX`` residues into
        the shared bridging-oxygen ``OM`` chemistry.

        Parameters
        ----------
        name : str, optional
            Output filename. Defaults to ``<name>.top``.

        Raises
        ------
        TypeError
            Raised when topology generation is requested for a non-slit input.
        """
        # Check input type
        if self._snapshot.source_kind != "silica_slit":
            raise TypeError("Helper topology output requires a silica-slit snapshot.")

        # Initialize
        link = self._link
        link += name if name else self._name+".top"

        # Copy master topology file
        template_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")
        utils.copy(os.path.join(template_dir, "topol.top"), link)

        # Open file
        with open(link, "a") as file_out:
            # Include topology
            for mol_short in self._short_list:
                if mol_short not in ["SI", "OM", "SL", "SLG", "SLX"]:
                    file_out.write("#include \""+mol_short+".itp\"\n")

            file_out.write("\n")
            file_out.write("[ system ]\n")
            file_out.write("Silica slit system generated by SilicaMS\n")

            file_out.write("\n")
            file_out.write("[ molecules ]\n")

            # Number of atoms
            for export_count in self._export_molecule_counts():
                file_out.write(
                    export_count.residue_name
                    + " "
                    + str(export_count.count)
                    + "\n"
                )

    def _bare_silica_charge_diagnostics_from_cache(self, cache, silica_topology):
        """Build bare-silica charge diagnostics from cached export records.

        Parameters
        ----------
        cache : _StructureExportCache
            Cached structure-export records in writer order.
        silica_topology : SilicaTopologyModel
            Resolved silica topology model whose assignments should be
            audited.

        Returns
        -------
        diagnostics : BareSilicaChargeDiagnostics
            Charge and coordination diagnostics for the finalized bare slit.

        Raises
        ------
        ValueError
            Raised when the wrapped slit contains non-bare residues or when a
            silica assignment cannot be resolved for one exported atom.
        """
        unsupported_residues = sorted(
            {
                record.residue_name
                for record in cache.atom_records
                if record.residue_name not in {"OM", "SI", "SL", "SLG"}
            }
        )
        if unsupported_residues:
            raise ValueError(
                "Bare slit charge diagnostics only support bare silica "
                f"residues. Found {unsupported_residues!r}."
            )

        role_counts = {
            "framework_silicon": 0,
            "framework_oxygen": 0,
            "silanol_silicon": 0,
            "silanol_oxygen": 0,
            "silanol_hydrogen": 0,
            "geminal_silicon": 0,
            "geminal_oxygen": 0,
            "geminal_hydrogen": 0,
        }
        for record in cache.atom_records:
            role_name = _silica_assignment_role_name(record)
            role_counts[role_name] += 1

        def contribution(role_name):
            assignment = getattr(silica_topology.atom_assignments, role_name)
            charge_per_atom = float(assignment.charge)
            atom_count = role_counts[role_name]
            return BareSilicaChargeContribution(
                atom_role=role_name,
                atom_type_name=assignment.atom_type_name,
                atom_count=atom_count,
                charge_per_atom=charge_per_atom,
                total_charge=atom_count * charge_per_atom,
            )

        framework_silicon = contribution("framework_silicon")
        framework_oxygen = contribution("framework_oxygen")
        silanol_silicon = contribution("silanol_silicon")
        silanol_oxygen = contribution("silanol_oxygen")
        silanol_hydrogen = contribution("silanol_hydrogen")
        geminal_silicon = contribution("geminal_silicon")
        geminal_oxygen = contribution("geminal_oxygen")
        geminal_hydrogen = contribution("geminal_hydrogen")

        total_silicon_count = (
            framework_silicon.atom_count
            + silanol_silicon.atom_count
            + geminal_silicon.atom_count
        )
        total_hydroxyl_count = (
            silanol_hydrogen.atom_count
            + geminal_hydrogen.atom_count
        )
        coordination_identity_left = 4 * total_silicon_count
        coordination_identity_right = (
            2 * framework_oxygen.atom_count
            + total_hydroxyl_count
        )
        total_charge = (
            framework_silicon.total_charge
            + framework_oxygen.total_charge
            + silanol_silicon.total_charge
            + silanol_oxygen.total_charge
            + silanol_hydrogen.total_charge
            + geminal_silicon.total_charge
            + geminal_oxygen.total_charge
            + geminal_hydrogen.total_charge
        )

        return BareSilicaChargeDiagnostics(
            framework_silicon=framework_silicon,
            framework_oxygen=framework_oxygen,
            silanol_silicon=silanol_silicon,
            silanol_oxygen=silanol_oxygen,
            silanol_hydrogen=silanol_hydrogen,
            geminal_silicon=geminal_silicon,
            geminal_oxygen=geminal_oxygen,
            geminal_hydrogen=geminal_hydrogen,
            silanol_site_count=silanol_silicon.atom_count,
            geminal_site_count=geminal_silicon.atom_count,
            total_silicon_count=total_silicon_count,
            total_hydroxyl_count=total_hydroxyl_count,
            coordination_identity_left=coordination_identity_left,
            coordination_identity_right=coordination_identity_right,
            coordination_identity_delta=(
                coordination_identity_left - coordination_identity_right
            ),
            total_charge=total_charge,
        )

    def bare_charge_diagnostics(self, silica_topology=None):
        """Return bare-silica charge diagnostics for a finalized slit export.

        Parameters
        ----------
        silica_topology : SilicaTopologyModel or None, optional
            Resolved silica topology model whose atom assignments should be
            audited. When omitted, the package defaults are used.

        Returns
        -------
        diagnostics : BareSilicaChargeDiagnostics
            Charge and coordination diagnostics for the finalized bare slit.

        Raises
        ------
        TypeError
            Raised when the input is not a silica-slit snapshot
            or when ``silica_topology`` has the wrong type.
        ValueError
            Raised when the wrapped slit is not finalized or when non-bare
            residues are present.
        """
        if self._snapshot.source_kind != "silica_slit":
            raise TypeError("Bare charge diagnostics require a silica-slit snapshot.")
        if not self._snapshot.is_finalized:
            raise ValueError("Bare charge diagnostics require a finalized slit snapshot.")
        if silica_topology is None:
            silica_topology = default_silica_topology()
        elif not isinstance(silica_topology, SilicaTopologyModel):
            raise TypeError(
                "GromacsTopologyWriter: silica_topology must be a SilicaTopologyModel instance "
                "or None."
            )

        cache = self._export_cache(use_atom_names=True)
        return self._bare_silica_charge_diagnostics_from_cache(
            cache,
            silica_topology,
        )

    def write_full_slit(
        self,
        name="",
        base_ligand_short="",
        silane_topology_config=None,
        silica_topology=None,
    ):
        """Write one self-contained full-slit GROMACS topology when supported.

        Parameters
        ----------
        name : str, optional
            Output topology filename. Defaults to ``<name>.top``.
        base_ligand_short : str, optional
            Base short name of the configured silane ligand, for example
            ``"TMS"``. Geminal variants are expected to use the same short
            name with a trailing ``"G"``.
        silane_topology_config : object or None, optional
            Optional silane topology configuration carrying ``itp_path``,
            ``moleculetype_name``, and optional ``geminal_cross_terms``. The
            supplied flat ITP is interpreted as one base post-condensation ``T3`` fragment
            whose total charge must already match the target derived from the
            resolved silica model. Retained scaffold ``O-Si-O`` cross angles
            use an explicit geminal-cross-term override when supplied and
            otherwise fall back to the active silica topology model.
        silica_topology : SilicaTopologyModel or None, optional
            Resolved editable silica topology model used for scaffold and
            graft-junction terms. When omitted, the package defaults are used.

        Returns
        -------
        charge_diagnostics : FunctionalizedSlitChargeDiagnostics or None
            Functionalized-slit charge diagnostics when a user-supplied silane
            topology bundle was assembled. Bare slit exports return ``None``.

        Raises
        ------
        TypeError
            Raised when the input is not a silica-slit snapshot.
        ValueError
            Raised when the slit is not finalized or when the available
            topology information is internally inconsistent. Bare slit export
            also raises when the finalized silica bookkeeping no longer
            preserves zero total charge under the active silica assignments.
            Functionalized export additionally raises when the supplied base
            ``T3`` fragment charge or the final assembled topology charge
            violate the enforced neutrality invariants.
        """
        if self._snapshot.source_kind != "silica_slit":
            raise TypeError("Full slit topology output requires a silica-slit snapshot.")
        if not self._snapshot.is_finalized:
            raise ValueError("Full slit topology output requires a finalized slit snapshot.")
        if silica_topology is None:
            silica_topology = default_silica_topology()
        elif not isinstance(silica_topology, SilicaTopologyModel):
            raise TypeError(
                "GromacsTopologyWriter: silica_topology must be a SilicaTopologyModel instance "
                "or None."
            )

        bundle = None
        ligand_shorts = set()
        bundle_atoms_by_index = {}
        bundle_atomtypes_by_name = {}
        geminal_cross_terms = None
        if silane_topology_config is not None:
            bundle = parse_flat_itp(
                silane_topology_config.itp_path,
                moleculetype_name=getattr(silane_topology_config, "moleculetype_name", ""),
            )
            if bundle.moleculetype.nrexcl != _FULL_SLIT_NREXCL:
                raise ValueError(
                    "Full slit topology export currently requires ligand "
                    f"nrexcl={_FULL_SLIT_NREXCL}. Parsed "
                    f"{bundle.moleculetype.nrexcl} from "
                    f"{silane_topology_config.itp_path!r}."
                )
            bundle_atoms_by_index = {
                atom.index: atom
                for atom in bundle.moleculetype.atoms
            }
            bundle_atomtypes_by_name = {
                atomtype.name: atomtype
                for atomtype in bundle.atomtypes
            }
            geminal_cross_terms = getattr(
                silane_topology_config,
                "geminal_cross_terms",
                None,
            )
            if base_ligand_short:
                ligand_shorts = {base_ligand_short, base_ligand_short + "G"}

        cache = self._export_cache(use_atom_names=True)
        graph = self._export_graph(use_atom_names=True)
        record_by_serial = {
            record.serial: record
            for record in cache.atom_records
        }
        attachment_record_by_molecule_index = {
            record.molecule_index: record
            for record in self._snapshot.attachments
        }

        unsupported_residues = sorted(
            {
                record.residue_name
                for record in cache.atom_records
                if record.residue_name not in {"OM", "SI", "SL", "SLG"}
                and record.residue_name not in ligand_shorts
            }
        )
        if unsupported_residues:
            raise ValueError(
                "Full slit topology export found unsupported finalized "
                f"residues: {unsupported_residues!r}."
            )

        functionalized_charge_diagnostics = None
        mount_atom_name = None
        expected_t3_fragment_charge = None
        observed_t3_fragment_charge = None
        t3_fragment_charge_delta = None
        geminal_added_oh_charge = None
        derived_t2_fragment_charge = None
        t2_site_count = 0
        t3_site_count = 0

        if bundle is not None:
            expected_t3_fragment_charge = (
                float(silica_topology.atom_assignments.silanol_silicon.charge)
                + float(silica_topology.atom_assignments.silanol_oxygen.charge)
                + float(silica_topology.atom_assignments.silanol_hydrogen.charge)
            )
            geminal_added_oh_charge = (
                float(silica_topology.atom_assignments.geminal_oxygen.charge)
                + float(silica_topology.atom_assignments.geminal_hydrogen.charge)
            )
            derived_t2_fragment_charge = (
                expected_t3_fragment_charge + geminal_added_oh_charge
            )
            observed_t3_fragment_charge = bundle.total_charge()
            t3_fragment_charge_delta = (
                observed_t3_fragment_charge - expected_t3_fragment_charge
            )

            if (
                abs(t3_fragment_charge_delta)
                > _FUNCTIONALIZED_CHARGE_TOLERANCE
            ):
                raise ValueError(
                    "The supplied silane base T3 fragment topology does not "
                    "match the expected charge target derived from the "
                    "resolved silica topology. Expected "
                    f"{expected_t3_fragment_charge:.6f}, observed "
                    f"{observed_t3_fragment_charge:.6f}, delta "
                    f"{t3_fragment_charge_delta:.6f}."
                )

            residue_ids_by_name = {}
            for record in cache.atom_records:
                residue_ids_by_name.setdefault(record.residue_name, set()).add(
                    record.residue_id
                )
            t2_site_count = len(
                residue_ids_by_name.get(base_ligand_short + "G", set())
            )
            t3_site_count = len(residue_ids_by_name.get(base_ligand_short, set()))

            if self._snapshot.attachments:
                first_attachment = self._snapshot.attachments[0]
                first_attachment_serials = cache.molecule_serials[
                    first_attachment.molecule_index
                ]
                mount_atom_name = record_by_serial[
                    first_attachment_serials[first_attachment.mount_atom_local_id]
                ].atom_name

            if t2_site_count > 0:
                if geminal_cross_terms is None:
                    raise ValueError(
                        "Geminal T2 full-topology export requires explicit "
                        "SilaneTopologyConfig.geminal_cross_terms."
                    )
                if mount_atom_name is None:
                    raise ValueError(
                        "Geminal T2 full-topology export requires at least "
                        "one attachment to resolve the mount atom name."
                    )
                if not bundle.has_atom_name(geminal_cross_terms.first_ligand_atom_name):
                    raise ValueError(
                        "Silane geminal cross terms reference unknown base "
                        "ligand atom name "
                        f"{geminal_cross_terms.first_ligand_atom_name!r}."
                    )
                if bundle.bond_by_names(
                    mount_atom_name,
                    geminal_cross_terms.first_ligand_atom_name,
                ) is None:
                    raise ValueError(
                        "Silane geminal cross terms require "
                        f"{geminal_cross_terms.first_ligand_atom_name!r} to "
                        "be directly bonded to the mount atom "
                        f"{mount_atom_name!r} in the base T3 topology."
                    )

        if bundle is None:
            diagnostics = self._bare_silica_charge_diagnostics_from_cache(
                cache,
                silica_topology,
            )
            if not diagnostics.coordination_identity_holds or not diagnostics.is_neutral:
                raise ValueError(
                    "Bare slit full-topology export must preserve zero total "
                    "charge under the current silica assignments. Observed "
                    f"total_charge={diagnostics.total_charge:.8f}, "
                    "coordination_identity_delta="
                    f"{diagnostics.coordination_identity_delta}."
                )

        silica_atomtypes = _silica_atomtypes_in_order(silica_topology)
        silica_atomtype_by_name = _silica_atomtype_lookup(silica_topology)

        def assignment_fields(assignment):
            atomtype = silica_atomtype_by_name.get(assignment.atom_type_name)
            if atomtype is None:
                raise ValueError(
                    "Silica topology assignment references unknown atomtype "
                    f"{assignment.atom_type_name!r}."
                )
            return assignment.atom_type_name, assignment.charge, assignment.mass

        def silica_atom_fields(record):
            role_name = _silica_assignment_role_name(record)
            return assignment_fields(
                getattr(silica_topology.atom_assignments, role_name)
            )

        def ligand_atom_fields(record):
            if bundle is None or record.residue_name not in ligand_shorts:
                return None

            if bundle.has_atom_name(record.atom_name):
                bundle_atom = bundle.atom_by_name(record.atom_name)
                mass = bundle_atom.mass
                if mass is None:
                    atomtype = bundle_atomtypes_by_name.get(bundle_atom.atom_type)
                    if atomtype is None:
                        raise ValueError(
                            "Bundle atom mass is missing and no matching "
                            f"[ atomtypes ] definition exists for "
                            f"{bundle_atom.atom_type!r} in {bundle.source_path!r}."
                        )
                    mass = atomtype.mass
                return bundle_atom.atom_type, bundle_atom.charge, mass

            if record.residue_name == base_ligand_short + "G":
                if record.atom_type == "O":
                    return assignment_fields(silica_topology.atom_assignments.geminal_oxygen)
                if record.atom_type == "H":
                    return assignment_fields(silica_topology.atom_assignments.geminal_hydrogen)

            raise ValueError(
                "Finalized ligand residue contains atoms that cannot be mapped "
                "to the supplied base ligand topology bundle: "
                f"{(record.residue_name, record.atom_name)!r}."
            )

        def is_generated_geminal_record(record, atom_type):
            return (
                bundle is not None
                and record.residue_name == base_ligand_short + "G"
                and record.atom_type == atom_type
                and not bundle.has_atom_name(record.atom_name)
            )

        atoms = []
        atomtype_order = list(silica_atomtypes)
        atomtype_by_name = {
            atomtype.name: atomtype
            for atomtype in atomtype_order
        }
        if bundle is not None:
            for atomtype in bundle.atomtypes:
                existing = atomtype_by_name.get(atomtype.name)
                if existing is not None:
                    if not existing.is_compatible_with(atomtype):
                        raise ValueError(
                            "Conflicting duplicate atomtype definition for "
                            f"{atomtype.name!r} between the internal silica "
                            "model and the supplied ligand topology bundle."
                        )
                    continue
                atomtype_by_name[atomtype.name] = atomtype
                atomtype_order.append(atomtype)

        for record in cache.atom_records:
            atom_fields = ligand_atom_fields(record)
            if atom_fields is None:
                atom_fields = silica_atom_fields(record)
            atom_type_name, charge_token, mass_token = atom_fields
            atoms.append(
                GromacsAtom(
                    index=record.serial,
                    atom_type=atom_type_name,
                    residue_number=record.residue_id,
                    residue_name=record.residue_name,
                    atom_name=record.atom_name,
                    charge_group=record.serial,
                    charge=_format_decimal_token(charge_token),
                    mass=_format_decimal_token(mass_token, places=4),
                )
            )

        bonds = []
        for bond in graph.bonds:
            record_a = record_by_serial[bond.atom_a]
            record_b = record_by_serial[bond.atom_b]
            bond_parameters = None

            if (
                bundle is not None
                and record_a.molecule_index == record_b.molecule_index
                and record_a.residue_name in ligand_shorts
                and record_b.residue_name in ligand_shorts
            ):
                bundle_bond = bundle.bond_by_names(
                    record_a.atom_name,
                    record_b.atom_name,
                )
                if bundle_bond is not None:
                    bond_parameters = bundle_bond.parameters

            if bond_parameters is None:
                elements = sorted(
                    (
                        db.get_element(record_a.atom_type),
                        db.get_element(record_b.atom_type),
                    )
                )
                if elements == ["H", "O"]:
                    bond_parameters = (
                        silica_topology
                        .bond_terms
                        .silanol_o_h
                        .to_gromacs_parameters()
                    )
                elif elements == ["O", "Si"]:
                    if bond.provenance == "graft_junction":
                        bond_parameters = (
                            silica_topology
                            .bond_terms
                            .graft_mount_scaffold_si_o
                            .to_gromacs_parameters()
                        )
                    else:
                        bond_parameters = (
                            silica_topology
                            .bond_terms
                            .framework_si_o
                            .to_gromacs_parameters()
                        )
                else:
                    raise ValueError(
                        "Unsupported bond environment for full slit topology "
                        f"export: {(record_a.residue_name, record_a.atom_name, record_b.residue_name, record_b.atom_name)!r}."
                    )

            bonds.append(
                GromacsBond(
                    atom_a=bond.atom_a,
                    atom_b=bond.atom_b,
                    parameters=bond_parameters,
                )
            )

        angles = []
        for angle in graph.angles:
            record_a = record_by_serial[angle.atom_a]
            record_b = record_by_serial[angle.atom_b]
            record_c = record_by_serial[angle.atom_c]
            angle_parameters = None

            if (
                bundle is not None
                and record_a.molecule_index == record_b.molecule_index == record_c.molecule_index
                and record_a.residue_name in ligand_shorts
                and record_b.residue_name in ligand_shorts
                and record_c.residue_name in ligand_shorts
            ):
                bundle_angle = bundle.angle_by_names(
                    record_a.atom_name,
                    record_b.atom_name,
                    record_c.atom_name,
                )
                if bundle_angle is not None:
                    angle_parameters = bundle_angle.parameters

            if angle_parameters is None:
                center_element = db.get_element(record_b.atom_type)
                outer_elements = sorted(
                    (
                        db.get_element(record_a.atom_type),
                        db.get_element(record_c.atom_type),
                    )
                )
                mount_cross_angle_role = None
                if geminal_cross_terms is not None:
                    mount_cross_angle_role = _full_slit_mount_ligand_cross_angle_role(
                        record_a,
                        record_b,
                        record_c,
                        ligand_shorts=ligand_shorts,
                        mount_atom_name=mount_atom_name,
                        first_ligand_atom_name=geminal_cross_terms.first_ligand_atom_name,
                        is_generated_geminal_record=is_generated_geminal_record,
                    )

                if (
                    geminal_cross_terms is not None
                    and center_element == "Si"
                    and record_b.residue_name == base_ligand_short + "G"
                    and mount_cross_angle_role == "geminal"
                ):
                    angle_parameters = (
                        geminal_cross_terms
                        .geminal_oxygen_mount_ligand_angle
                    )
                elif mount_cross_angle_role == "scaffold":
                    if (
                        geminal_cross_terms
                        .scaffold_oxygen_mount_ligand_angle
                        is not None
                    ):
                        angle_parameters = (
                            geminal_cross_terms
                            .scaffold_oxygen_mount_ligand_angle
                        )
                    elif outer_elements == ["O", "O"]:
                        angle_parameters = (
                            silica_topology
                            .angle_terms
                            .graft_oxygen_mount_oxygen
                            .to_gromacs_parameters()
                        )
                    else:
                        raise ValueError(
                            "Full slit topology export requires explicit "
                            "SilaneGeminalCrossTerms."
                            "scaffold_oxygen_mount_ligand_angle for "
                            "retained scaffold O-Si(mount)-first_ligand_atom "
                            f"angles when the first ligand atom is not oxygen. "
                            f"Encountered {(record_a.residue_name, record_a.atom_name, record_b.residue_name, record_b.atom_name, record_c.residue_name, record_c.atom_name)!r}."
                        )
                elif center_element == "O" and outer_elements == ["H", "Si"]:
                    angle_parameters = (
                        silica_topology
                        .angle_terms
                        .silanol_si_o_h
                        .to_gromacs_parameters()
                    )
                elif center_element == "O" and outer_elements == ["Si", "Si"]:
                    if (
                        record_b.residue_name == "OM"
                        and (
                            (record_a.residue_name == "SI" and record_c.residue_name in ligand_shorts)
                            or (record_c.residue_name == "SI" and record_a.residue_name in ligand_shorts)
                        )
                    ):
                        angle_parameters = (
                            silica_topology
                            .angle_terms
                            .graft_scaffold_si_scaffold_o_mount
                            .to_gromacs_parameters()
                        )
                    else:
                        angle_parameters = (
                            silica_topology
                            .angle_terms
                            .framework_si_o_si
                            .to_gromacs_parameters()
                        )
                elif center_element == "Si" and outer_elements == ["O", "O"]:
                    if record_b.residue_name in ligand_shorts:
                        angle_parameters = (
                            silica_topology
                            .angle_terms
                            .graft_oxygen_mount_oxygen
                            .to_gromacs_parameters()
                        )
                    else:
                        angle_parameters = (
                            silica_topology
                            .angle_terms
                            .silanol_o_si_o
                            .to_gromacs_parameters()
                        )
                else:
                    raise ValueError(
                        "Unsupported angle environment for full slit topology "
                        f"export: {(record_a.residue_name, record_a.atom_name, record_b.residue_name, record_b.atom_name, record_c.residue_name, record_c.atom_name)!r}."
                    )

            if angle_parameters is None:
                raise ValueError(
                    "Full slit topology export could not resolve angle "
                    "parameters for "
                    f"{(record_a.residue_name, record_a.atom_name, record_b.residue_name, record_b.atom_name, record_c.residue_name, record_c.atom_name)!r}."
                )

            angles.append(
                GromacsAngle(
                    atom_a=angle.atom_a,
                    atom_b=angle.atom_b,
                    atom_c=angle.atom_c,
                    parameters=angle_parameters,
                )
            )

        pairs = []
        dihedrals = []
        if bundle is not None:
            for molecule_index, (mol, serials) in enumerate(
                zip(self._mols, cache.molecule_serials)
            ):
                if mol.get_short() not in ligand_shorts:
                    continue

                local_name_by_serial = {
                    serial: record_by_serial[serial].atom_name
                    for serial in serials
                }
                serial_by_bundle_name = {
                    atom_name: serial
                    for serial, atom_name in local_name_by_serial.items()
                    if bundle.has_atom_name(atom_name)
                }
                missing_bundle_names = sorted(
                    name
                    for name in bundle.atom_index_by_name
                    if name not in serial_by_bundle_name
                )
                if missing_bundle_names:
                    raise ValueError(
                        "Finalized ligand molecule is missing atom names "
                        f"required by the supplied topology bundle: "
                        f"{missing_bundle_names}."
                    )

                for pair in bundle.moleculetype.pairs:
                    atom_name_a = bundle_atoms_by_index[pair.atom_a].atom_name
                    atom_name_b = bundle_atoms_by_index[pair.atom_b].atom_name
                    pairs.append(
                        GromacsPair(
                            atom_a=serial_by_bundle_name[atom_name_a],
                            atom_b=serial_by_bundle_name[atom_name_b],
                            function=pair.function,
                            parameters=pair.parameters,
                        )
                    )

                for dihedral in bundle.moleculetype.dihedrals:
                    atom_name_a = bundle_atoms_by_index[dihedral.atom_a].atom_name
                    atom_name_b = bundle_atoms_by_index[dihedral.atom_b].atom_name
                    atom_name_c = bundle_atoms_by_index[dihedral.atom_c].atom_name
                    atom_name_d = bundle_atoms_by_index[dihedral.atom_d].atom_name
                    dihedrals.append(
                        GromacsDihedral(
                            atom_a=serial_by_bundle_name[atom_name_a],
                            atom_b=serial_by_bundle_name[atom_name_b],
                            atom_c=serial_by_bundle_name[atom_name_c],
                            atom_d=serial_by_bundle_name[atom_name_d],
                            function=dihedral.function,
                            parameters=dihedral.parameters,
                        )
                    )

                if (
                    geminal_cross_terms is not None
                    and mol.get_short() == base_ligand_short + "G"
                ):
                    generated_geminal_oxygen_serials = [
                        serial
                        for serial in serials
                        if is_generated_geminal_record(record_by_serial[serial], "O")
                    ]
                    if len(generated_geminal_oxygen_serials) != 1:
                        raise ValueError(
                            "Geminal T2 topology export expects exactly one "
                            "internally generated hydroxyl oxygen per geminal "
                            f"residue. Found {len(generated_geminal_oxygen_serials)} "
                            f"for residue {mol.get_short()!r}."
                        )
                    attachment_record = attachment_record_by_molecule_index.get(
                        molecule_index
                    )
                    if attachment_record is None:
                        raise ValueError(
                            "Geminal T2 topology export could not resolve the "
                            "attachment record for one finalized ligand "
                            "molecule."
                        )
                    mount_serial = serials[attachment_record.mount_atom_local_id]
                    first_ligand_atom_serial = serial_by_bundle_name.get(
                        geminal_cross_terms.first_ligand_atom_name
                    )
                    if first_ligand_atom_serial is None:
                        raise ValueError(
                            "Geminal T2 topology export could not resolve "
                            "the configured first ligand atom "
                            f"{geminal_cross_terms.first_ligand_atom_name!r} "
                            "inside one finalized geminal residue."
                        )
                    for dihedral_spec in geminal_cross_terms.geminal_dihedrals:
                        fourth_atom_serial = serial_by_bundle_name.get(
                            dihedral_spec.fourth_atom_name
                        )
                        if fourth_atom_serial is None:
                            raise ValueError(
                                "Geminal T2 topology export references "
                                "unknown ligand atom "
                                f"{dihedral_spec.fourth_atom_name!r} in "
                                "SilaneTopologyConfig.geminal_cross_terms."
                            )
                        dihedrals.append(
                            GromacsDihedral(
                                atom_a=generated_geminal_oxygen_serials[0],
                                atom_b=mount_serial,
                                atom_c=first_ligand_atom_serial,
                                atom_d=fourth_atom_serial,
                                function=dihedral_spec.function,
                                parameters=dihedral_spec.parameters,
                            )
                        )

        top_filename = name if name else self._name + ".top"
        if not top_filename.endswith(".top"):
            top_filename = top_filename + ".top"
        itp_filename = os.path.splitext(top_filename)[0] + ".itp"
        top_link = self._link + top_filename
        itp_link = self._link + os.path.basename(itp_filename)

        molecule_name = _sanitize_gromacs_identifier(
            os.path.splitext(os.path.basename(itp_filename))[0],
            fallback="SLIT",
        )
        molecule_type = GromacsMoleculeType(
            name=molecule_name,
            nrexcl=_FULL_SLIT_NREXCL,
            atoms=tuple(atoms),
            bonds=tuple(sorted(bonds, key=lambda item: (item.atom_a, item.atom_b))),
            pairs=tuple(sorted(pairs, key=lambda item: (item.atom_a, item.atom_b, item.function))),
            angles=tuple(sorted(angles, key=lambda item: (item.atom_b, item.atom_a, item.atom_c))),
            dihedrals=tuple(
                sorted(
                    dihedrals,
                    key=lambda item: (item.atom_b, item.atom_c, item.atom_a, item.atom_d, item.function),
                )
            ),
        )

        if bundle is not None:
            final_total_charge = sum(float(atom.charge) for atom in atoms)
            functionalized_charge_diagnostics = FunctionalizedSlitChargeDiagnostics(
                expected_t3_fragment_charge=expected_t3_fragment_charge,
                observed_t3_fragment_charge=observed_t3_fragment_charge,
                t3_fragment_charge_delta=t3_fragment_charge_delta,
                derived_t2_fragment_charge=derived_t2_fragment_charge,
                geminal_added_oh_charge=geminal_added_oh_charge,
                t2_site_count=t2_site_count,
                t3_site_count=t3_site_count,
                final_total_charge=final_total_charge,
                tolerance=_FUNCTIONALIZED_CHARGE_TOLERANCE,
            )
            if not functionalized_charge_diagnostics.is_final_topology_neutral:
                raise ValueError(
                    "Functionalized full-slit topology export must remain "
                    "neutral under the current silica assignments and the "
                    "user-supplied silane fragment charges. Observed final "
                    f"total charge {final_total_charge:.6f}."
                )

        with open(itp_link, "w") as file_out:
            file_out.write(render_itp(atomtype_order, molecule_type))

        with open(top_link, "w") as file_out:
            file_out.write(
                render_top(
                    include_filename=os.path.basename(itp_link),
                    system_name="Silica slit system generated by SilicaMS",
                    molecule_name=molecule_type.name,
                )
            )

        return functionalized_charge_diagnostics

    def write_grid_itp(self, name="", charges=None):
        """Write the ``grid.itp`` topology template for silica grid atoms.

        Parameters
        ----------
        name : str, optional
            Output filename. Defaults to ``grid.itp``.
        charges : dict, optional
            Charge mapping containing ``"si"`` and ``"om"`` entries for the
            silicon and bridging-oxygen grid atoms. The helper template uses
            ``OM`` as the only exported identity for bridging silica oxygens.
        """
        charges = {"si": 1.28, "om": -0.64} if charges is None else charges

        # Initialize
        link = self._link
        link += name if name else "grid.itp"

        # Copy grid file
        template_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "templates")
        utils.copy(os.path.join(template_dir, "grid.itp"), link)

        # Replace charges
        utils.replace(link, "CHARGEO", "%8.6f" % charges["om"])
        utils.replace(link, "CHARGESI", "%8.6f" % charges["si"])
